In [1]:
import numpy as np
import pandas as pd
import numpy as np
import pandas as pd
import sys
import csv
import json

csv.field_size_limit(1000000000000000000)

131072

In [2]:
# importing the master file from a perviously piclkled dataframe
master = pd.read_pickle("./master.pkl")

In [3]:
# importing the yearly device files as dataframes
device2000 = pd.read_csv('DEVICE2000.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2001 = pd.read_csv('DEVICE2001.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2002 = pd.read_csv('DEVICE2002.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2003 = pd.read_csv('DEVICE2003.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2004 = pd.read_csv('DEVICE2004.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2005 = pd.read_csv('DEVICE2005.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2006 = pd.read_csv('DEVICE2006.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2007 = pd.read_csv('DEVICE2007.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2008 = pd.read_csv('DEVICE2008.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2009 = pd.read_csv('DEVICE2009.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2010 = pd.read_csv('DEVICE2010.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2011 = pd.read_csv('DEVICE2011.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2012 = pd.read_csv('DEVICE2012.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2013 = pd.read_csv('DEVICE2013.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2014 = pd.read_csv('DEVICE2014.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2015 = pd.read_csv('DEVICE2015.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2016 = pd.read_csv('DEVICE2016.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2017 = pd.read_csv('DEVICE2017.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2018 = pd.read_csv('DEVICE2018.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2019 = pd.read_csv('DEVICE2019.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
device2020 = pd.read_csv('DEVICE2020.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)

In [4]:
# importing the yearly text files as dataframes
foitext2000 = pd.read_csv('foitext2000.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2001 = pd.read_csv('foitext2001.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2002 = pd.read_csv('foitext2002.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2003 = pd.read_csv('foitext2003.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2004 = pd.read_csv('foitext2004.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2005 = pd.read_csv('foitext2005.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2006 = pd.read_csv('foitext2006.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2007 = pd.read_csv('foitext2007.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2008 = pd.read_csv('foitext2008.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2009 = pd.read_csv('foitext2009.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2010 = pd.read_csv('foitext2010.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2011 = pd.read_csv('foitext2011.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2012 = pd.read_csv('foitext2012.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2013 = pd.read_csv('foitext2013.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2014 = pd.read_csv('foitext2014.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2015 = pd.read_csv('foitext2015.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2016 = pd.read_csv('foitext2016.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2017 = pd.read_csv('foitext2017.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2018 = pd.read_csv('foitext2018.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2019 = pd.read_csv('foitext2019.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)
foitext2020 = pd.read_csv('foitext2020.txt', sep="|", header = 0, dtype=str, engine='python', quoting=3)

In [5]:
def deleteNull(df):
    for ind in df.index:
        if df.isnull()['FOI_TEXT'][ind] == True:
            df.drop(labels=[ind],axis=0,inplace=True)

In [6]:
def containsWord(s, w):
    return (' ' + str(w) + ' ') in (' ' + str(s) + ' ')

In [55]:
def selectCohortOne(df):
    dfLWS = df[df['DEVICE_REPORT_PRODUCT_CODE']=='LWS']
    dfMRM = df[df['DEVICE_REPORT_PRODUCT_CODE']=='MRM']
    dfNIK = df[df['DEVICE_REPORT_PRODUCT_CODE']=='NIK']
    dfNVY = df[df['DEVICE_REPORT_PRODUCT_CODE']=='NVY']
    
    df = pd.concat([dfLWS, dfMRM, dfNIK, dfNVY])

In [51]:
allData2000 = pd.merge(master, device2000, on="MDR_REPORT_KEY")
allData2000 = pd.merge(allData2000, foitext2000, on="MDR_REPORT_KEY")

In [52]:
allData2000.head()

,MDR_REPORT_KEY,EVENT_KEY,REPORT_NUMBER,REPORT_SOURCE_CODE,MANUFACTURER_LINK_FLAG_,NUMBER_DEVICES_IN_EVENT,NUMBER_PATIENTS_IN_EVENT,DATE_RECEIVED_x,ADVERSE_EVENT_FLAG,PRODUCT_PROBLEM_FLAG,...,DATE_RETURNED_TO_MANUFACTURER,DEVICE_REPORT_PRODUCT_CODE,DEVICE_AGE_TEXT,DEVICE_EVALUATED_BY_MANUFACTUR,COMBINATION_PRODUCT_FLAG,MDR_TEXT_KEY,TEXT_TYPE_CODE,PATIENT_SEQUENCE_NUMBER,DATE_REPORT_y,FOI_TEXT
0,257047,NaN,2183996-1999-00106,M,Y,NaN,NaN,01/02/2000,Y,N,...,NaN,LZG,NaN,R,NaN,146403,D,1,NaN,PT HOSPITALIZED FOR HYPERGLYCEMIA. PT CHANGED ...
1,257056,NaN,3019090-2000-00001,M,Y,NaN,NaN,01/03/2000,Y,Y,...,NaN,FQP,NaN,Y,NaN,146552,D,1,NaN,A BULB BURST IN THE SURGICAL LIGHT DURING A PR...
2,257089,NaN,1618732-1999-00280,M,Y,NaN,NaN,01/03/2000,Y,N,...,NaN,LYY,UNKNOWN,N,NaN,204106,D,1,NaN,PLAINTIFF ALLEGES PHYSICAL & EMOTIONAL DAMAGES...
3,257095,NaN,1618732-1999-00278,M,Y,NaN,NaN,01/03/2000,N,*,...,NaN,LYY,UNKNOWN,N,NaN,19776217,D,1,NaN,HUMAN REACTION. PLAINTIFF ALLEGES PHYSICAL AND...
4,257101,NaN,1618732-1999-00279,M,Y,NaN,NaN,01/03/2000,N,*,...,NaN,LYY,UNKNOWN,N,NaN,146718,D,1,NaN,HUMAN REACTION TO LATEX SURGICAL AND/OR MEDICA...

In [53]:
allData2000.shape

(51171, 114)

In [56]:
selectCohortOne(allData2000)

In [57]:
allData2000.head()

,MDR_REPORT_KEY,EVENT_KEY,REPORT_NUMBER,REPORT_SOURCE_CODE,MANUFACTURER_LINK_FLAG_,NUMBER_DEVICES_IN_EVENT,NUMBER_PATIENTS_IN_EVENT,DATE_RECEIVED_x,ADVERSE_EVENT_FLAG,PRODUCT_PROBLEM_FLAG,...,DATE_RETURNED_TO_MANUFACTURER,DEVICE_REPORT_PRODUCT_CODE,DEVICE_AGE_TEXT,DEVICE_EVALUATED_BY_MANUFACTUR,COMBINATION_PRODUCT_FLAG,MDR_TEXT_KEY,TEXT_TYPE_CODE,PATIENT_SEQUENCE_NUMBER,DATE_REPORT_y,FOI_TEXT
0,257047,NaN,2183996-1999-00106,M,Y,NaN,NaN,01/02/2000,Y,N,...,NaN,LZG,NaN,R,NaN,146403,D,1,NaN,PT HOSPITALIZED FOR HYPERGLYCEMIA. PT CHANGED ...
1,257056,NaN,3019090-2000-00001,M,Y,NaN,NaN,01/03/2000,Y,Y,...,NaN,FQP,NaN,Y,NaN,146552,D,1,NaN,A BULB BURST IN THE SURGICAL LIGHT DURING A PR...
2,257089,NaN,1618732-1999-00280,M,Y,NaN,NaN,01/03/2000,Y,N,...,NaN,LYY,UNKNOWN,N,NaN,204106,D,1,NaN,PLAINTIFF ALLEGES PHYSICAL & EMOTIONAL DAMAGES...
3,257095,NaN,1618732-1999-00278,M,Y,NaN,NaN,01/03/2000,N,*,...,NaN,LYY,UNKNOWN,N,NaN,19776217,D,1,NaN,HUMAN REACTION. PLAINTIFF ALLEGES PHYSICAL AND...
4,257101,NaN,1618732-1999-00279,M,Y,NaN,NaN,01/03/2000,N,*,...,NaN,LYY,UNKNOWN,N,NaN,146718,D,1,NaN,HUMAN REACTION TO LATEX SURGICAL AND/OR MEDICA...

In [58]:
allData2000.shape

(51171, 114)

In [59]:
l = [allData2000[allData2000['DEVICE_REPORT_PRODUCT_CODE']=='LWS'],
     allData2000[allData2000['DEVICE_REPORT_PRODUCT_CODE']=='MRM'],
     allData2000[allData2000['DEVICE_REPORT_PRODUCT_CODE']=='NIK'],
     allData2000[allData2000['DEVICE_REPORT_PRODUCT_CODE']=='NVY']]

pd.concat(l)

,MDR_REPORT_KEY,EVENT_KEY,REPORT_NUMBER,REPORT_SOURCE_CODE,MANUFACTURER_LINK_FLAG_,NUMBER_DEVICES_IN_EVENT,NUMBER_PATIENTS_IN_EVENT,DATE_RECEIVED_x,ADVERSE_EVENT_FLAG,PRODUCT_PROBLEM_FLAG,...,DATE_RETURNED_TO_MANUFACTURER,DEVICE_REPORT_PRODUCT_CODE,DEVICE_AGE_TEXT,DEVICE_EVALUATED_BY_MANUFACTUR,COMBINATION_PRODUCT_FLAG,MDR_TEXT_KEY,TEXT_TYPE_CODE,PATIENT_SEQUENCE_NUMBER,DATE_REPORT_y,FOI_TEXT
73,257484,NaN,2938836-2000-00003,M,Y,NaN,NaN,01/06/2000,Y,N,...,NaN,LWS,3 YR,Y,NaN,147733,D,1,NaN,THE PT PRESENTED AT THE CLINIC COMPLAINING OF ...
221,257721,NaN,MW1017857,P,N,NaN,NaN,01/06/2000,N,Y,...,NaN,LWS,NaN,NaN,NaN,161563,D,1,NaN,"DURING ROUTINE EVAL ON 12/18/1999, ERROR WHILE..."
272,257784,NaN,257784,U,N,NaN,NaN,01/04/2000,N,Y,...,NaN,LWS,*,NaN,NaN,161864,D,1,NaN,IMPLANTABLE CARDIOVERTER DEFIBRILLATOR WITH RE...
288,257800,NaN,2938836-2000-00002,M,Y,NaN,NaN,02/29/2000,Y,N,...,1999/12/23,LWS,9 MO,Y,NaN,177535,D,1,NaN,"DURING A ROUTINE FOLLOW-UP, AN ""EXCEPTION 13"" ..."
289,257801,NaN,2938836-2000-00004,M,Y,NaN,NaN,01/07/2000,Y,N,...,1999/12/23,LWS,2 YR,Y,NaN,206042,D,1,NaN,"DURING A ROUTINE FOLLOW-UP, A BATTERY VOLTAGE ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50858,309811,NaN,309811,U,N,NaN,NaN,12/22/2000,N,Y,...,NaN,LWS,4 YR,NaN,NaN,139918,D,1,NaN,PT HAD INTERNAL CARDIOVERTER-DEFIBRILLATOR PLA...
50859,309811,NaN,309811,U,N,NaN,NaN,12/22/2000,N,Y,...,NaN,LWS,4 YR,NaN,NaN,235011,D,1,NaN,ADD'L INFO REC'D FROM MFR 1/24/2001: MIDDLE IN...
51114,310059,NaN,2938836-2000-00307,M,Y,NaN,NaN,12/19/2000,Y,N,...,2000/12/05,LWS,4.6 YR,N,NaN,15712581,D,1,NaN,ST JUDE MEDICAL WAS NOTIFIED THAT THE TRANSVEN...
51117,310063,NaN,2938836-2000-00294,M,Y,NaN,NaN,12/19/2000,Y,N,...,2000/11/21,LWS,1.4 YR,Y,NaN,20469407,D,1,NaN,ST JUDE MEDICAL WAS NOTIFIED THAT THE DEVICE W...
13093,271849,NaN,MW1018547,P,N,NaN,NaN,03/23/2000,N,Y,...,NaN,NIK,NaN,NaN,NaN,19493952,D,1,NaN,IMPLANTED DEFIBRILLATOR MALFUNCTION. UNABLE TO...